version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  test:
    docker:
      - image: 'cimg/node:12.22-browser'
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - node/install:
          install-yarn: true
          node-version: 12
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn link
      - run:
          name: Test ember
          command: yarn test:ember
      - run:
          name: Test compat
          command: yarn test:ember-compatibility

workflows:
  test-frontend:
    jobs:
      - test
